name = "Sardelki"
author = "sosiski.lol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "272a2f5e583ed8692dfdf2ee3389820b8aa38fe9c49b17fe42339658633cbff2"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
