name = "Sardelki"
author = "sosiski.lol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a260e69024ee9005d509012f544933cd0c21c8f9fb0ba0b10a2a6cc0357f3c6"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
