name = "Sardelki"
author = "sosiski.lol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c39ed5178bd30960c31262469d303e176fe9ccf555f2ad99e15b1cd8bae60f3"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
