name = "Sardelki"
author = "sosiski.lol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5240d9b6aedaa7ee0957fde4b3fa72a9e7cd77762a8618fb2108154e315cccb3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
