name = "Sardelki"
author = "sosiski.lol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "583e161bff18caf4c18e8c69a66157a5eff9940e91054532b3c04ef4275e325b"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
