name = "Ssmp Modded"
author = "sosiski.lol"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c07faf7aecf1a0af2e9c8ef7b3cc85a0a381d4e1178362d7e812eb8e2214b62b"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
