name = "Sardelki"
author = "sosiski.lol"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be65025fc02c1420787823217e4072dfb1ceee9eb00023ec4785ea02bf591ffb"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
